### ISSUE TITLE
[website] This domain is parked

### ISSUE THREAD

**Issue by ghost** [FrancescoRigoni/GameBoyEmulator#1]
Your site on Wordpress is parked, I'd like to see all your posts related to emulation, but for some reason your site does not want to open.

**Comment by FrancescoRigoni** [comment]
Hi :) unfortunately I had to stop my activity on the website since I do not
have time to properly work on it anymore, I'm very sorry.
You can checkout the code of my emulators on my GitHub, and if you have
question just write me and I'll try to answer best I can.

Here's my email: francesco.rigoni@gmail.com

Francesco

Il giorno sab 22 giu 2019 alle ore 03:33 Esdras Tarsis <
notifications@github.com> ha scritto:

**Comment by ghost** [comment]
Oh, I hope everything goes well with your site and that it comes back active, it is very useful for those starting in the area of ​​emulators (like me), closing...
